import type { Metadata } from "next";
import { Download, Mail, ShieldCheck } from "lucide-react";

export const metadata: Metadata = { title: "Delivery", robots: { index: false, follow: false } };

const intakeHref = `mailto:pckautovic@gmail.com?subject=${encodeURIComponent("TraceNotice paid intake")}&body=${encodeURIComponent("Hi Predrag,\n\nPayPal payer email: \nPlan purchased: €190 / €490 / €2,500\nPublic AI surface URL(s): \nCompany / product: \nNotes: \n\nPublic/non-confidential information only.")}`;

export default function ThanksPage(){
  return <div className="mx-auto max-w-5xl px-5 py-16 lg:px-8 lg:py-24"><div className="rounded-[2.5rem] border border-[#A6E878]/25 bg-[#0c1714] p-7 md:p-10"><div className="flex items-center gap-3 text-[#A6E878]"><ShieldCheck/><span className="text-xs font-black uppercase tracking-[.18em]">After PayPal</span></div><h1 className="mt-6 text-5xl font-black tracking-[-.055em] md:text-7xl">Send the surface. Start the work.</h1><p className="mt-5 max-w-3xl text-lg leading-8 text-white/64">After payment, email the PayPal payer email and the public AI surface URL. That gives TraceNotice enough to match the payment to the fixed-scope work without asking you to post anything publicly.</p><div className="mt-10 grid gap-4 md:grid-cols-2"><a href={intakeHref} className="cta-green rounded-3xl bg-[#A6E878] p-6 text-[#07100e]"><Mail/><h2 className="mt-8 text-2xl font-black">Send paid intake</h2><p className="mt-2 text-sm leading-6 opacity-65">Prefilled private email. Include only public/non-confidential surface information.</p></a><a href="/downloads/implementation-pack.md" download className="rounded-3xl border border-white/10 bg-white/[.025] p-6"><Download className="text-[#A6E878]"/><h2 className="mt-8 text-2xl font-black">Download implementation pack</h2><p className="mt-2 text-sm leading-6 text-white/64">Surface inventory, control mapping, QA, evidence capture, remediation, and reviewer handoff templates.</p></a></div><p className="mt-6 text-xs leading-5 text-white/48">Returning to this page does not confirm payment. TraceNotice counts revenue only after PayPal confirms captured/received funds.</p></div></div>;
}
